---
services:
  django:
    container_name: django
    build: ./django
    volumes:
      - ./django/app:/data/app
      - static:/data/app/django_project/static
      - media:/data/app/django_project/media
    expose:
      - 8000
    env_file:
      - ./django/.env
      - ./postgres/.env
      - .env
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    container_name: postgres
    image: postgres:latest
    volumes:
      - prostgres_data:/var/lib/postgresql/data
    expose:
      - 5432
    env_file:
      - ./postgres/.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U djangouser -d djangodb"]
      interval: 5s
      timeout: 5s
      retries: 5

  nginx:
    container_name: nginx
    build: ./nginx
    volumes:
      - static:/data/app/static:ro
      - media:/data/app/media:ro
    ports:
      - 80:80
    depends_on:
      - django

volumes:
  prostgres_data:
  static:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./django/app/django_project/static
  media:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./django/app/django_project/media
...