FROM python:3.10
WORKDIR /data/

RUN groupadd -g 1000 user && \
    useradd -u 1000 -g 1000 -d /data/ user && \
    chown -R 1000:1000 /data/

ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

RUN pip install --upgrade pip --no-cache-dir
COPY --chown=1000:1000 requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt


COPY --chown=1000:1000 ./app/ /data/app/
WORKDIR /data/app

USER user

COPY entrypoint.sh /data/
ENTRYPOINT ["/data/entrypoint.sh"]
